# Generated by Django 2.2 on 2021-09-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210911_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created',
        ),
        migrations.RemoveField(
            model_name='products',
            name='updated',
        ),
    ]
