# Generated by Django 2.2 on 2021-09-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210913_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='available',
        ),
        migrations.RemoveField(
            model_name='products',
            name='created',
        ),
        migrations.RemoveField(
            model_name='products',
            name='updated',
        ),
    ]
