# Generated by Django 2.2 on 2021-09-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_products_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='available',
        ),
    ]
