# Generated by Django 2.2 on 2021-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_products_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
